Failure in python_extra_output.py:

  There were no remaining checks left to match stdout:2:
    Second

  Context:
    First
    Second <= no more checks

  when running command:
    /usr/bin/python3 python_extra_output.py
